name = "eweos-bot"
main = "src/index.js"
compatibility_date = "2024-07-05"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENV_BOT_WORKFLOW_CHANNEL = "-1002247523652"
ENV_GITHUB_APP_ID = "337143"
ENV_GITHUB_APP_INSTALL = "37785080"

[observability]
enabled = true
