name = "eweos-bot"
main = "src/index.js"
compatibility_date = "2025-07-09"

[vars]
ENV_BOT_WORKFLOW_CHANNEL = "-1002247523652"
ENV_GITHUB_APP_ID = "337143"
ENV_GITHUB_APP_INSTALL = "37785080"

[observability]
enabled = true
